/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 July, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.23.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meraki

import (
	"encoding/json"
)

// GetNetworkFirmwareUpgrades200ResponseProducts The network devices to be updated
type GetNetworkFirmwareUpgrades200ResponseProducts struct {
	Wireless *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"wireless,omitempty"`
	Switch *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"switch,omitempty"`
	Appliance *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"appliance,omitempty"`
	Camera *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"camera,omitempty"`
	VmxHost *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"vmxHost,omitempty"`
	Environmental *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"environmental,omitempty"`
	Sensor *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"sensor,omitempty"`
	CellularGateway *GetNetworkFirmwareUpgrades200ResponseProductsWireless `json:"cellularGateway,omitempty"`
}

// NewGetNetworkFirmwareUpgrades200ResponseProducts instantiates a new GetNetworkFirmwareUpgrades200ResponseProducts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkFirmwareUpgrades200ResponseProducts() *GetNetworkFirmwareUpgrades200ResponseProducts {
	this := GetNetworkFirmwareUpgrades200ResponseProducts{}
	return &this
}

// NewGetNetworkFirmwareUpgrades200ResponseProductsWithDefaults instantiates a new GetNetworkFirmwareUpgrades200ResponseProducts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkFirmwareUpgrades200ResponseProductsWithDefaults() *GetNetworkFirmwareUpgrades200ResponseProducts {
	this := GetNetworkFirmwareUpgrades200ResponseProducts{}
	return &this
}

// GetWireless returns the Wireless field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetWireless() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Wireless == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Wireless
}

// GetWirelessOk returns a tuple with the Wireless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetWirelessOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Wireless == nil {
		return nil, false
	}
	return o.Wireless, true
}

// HasWireless returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasWireless() bool {
	if o != nil && o.Wireless != nil {
		return true
	}

	return false
}

// SetWireless gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Wireless field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetWireless(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Wireless = &v
}

// GetSwitch returns the Switch field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetSwitch() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Switch == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Switch
}

// GetSwitchOk returns a tuple with the Switch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetSwitchOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Switch == nil {
		return nil, false
	}
	return o.Switch, true
}

// HasSwitch returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasSwitch() bool {
	if o != nil && o.Switch != nil {
		return true
	}

	return false
}

// SetSwitch gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Switch field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetSwitch(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Switch = &v
}

// GetAppliance returns the Appliance field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetAppliance() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Appliance == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Appliance
}

// GetApplianceOk returns a tuple with the Appliance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetApplianceOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Appliance == nil {
		return nil, false
	}
	return o.Appliance, true
}

// HasAppliance returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasAppliance() bool {
	if o != nil && o.Appliance != nil {
		return true
	}

	return false
}

// SetAppliance gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Appliance field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetAppliance(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Appliance = &v
}

// GetCamera returns the Camera field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetCamera() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Camera == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Camera
}

// GetCameraOk returns a tuple with the Camera field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetCameraOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Camera == nil {
		return nil, false
	}
	return o.Camera, true
}

// HasCamera returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasCamera() bool {
	if o != nil && o.Camera != nil {
		return true
	}

	return false
}

// SetCamera gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Camera field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetCamera(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Camera = &v
}

// GetVmxHost returns the VmxHost field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetVmxHost() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.VmxHost == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.VmxHost
}

// GetVmxHostOk returns a tuple with the VmxHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetVmxHostOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.VmxHost == nil {
		return nil, false
	}
	return o.VmxHost, true
}

// HasVmxHost returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasVmxHost() bool {
	if o != nil && o.VmxHost != nil {
		return true
	}

	return false
}

// SetVmxHost gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the VmxHost field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetVmxHost(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.VmxHost = &v
}

// GetEnvironmental returns the Environmental field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetEnvironmental() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Environmental == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Environmental
}

// GetEnvironmentalOk returns a tuple with the Environmental field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetEnvironmentalOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Environmental == nil {
		return nil, false
	}
	return o.Environmental, true
}

// HasEnvironmental returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasEnvironmental() bool {
	if o != nil && o.Environmental != nil {
		return true
	}

	return false
}

// SetEnvironmental gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Environmental field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetEnvironmental(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Environmental = &v
}

// GetSensor returns the Sensor field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetSensor() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.Sensor == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.Sensor
}

// GetSensorOk returns a tuple with the Sensor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetSensorOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.Sensor == nil {
		return nil, false
	}
	return o.Sensor, true
}

// HasSensor returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasSensor() bool {
	if o != nil && o.Sensor != nil {
		return true
	}

	return false
}

// SetSensor gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the Sensor field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetSensor(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.Sensor = &v
}

// GetCellularGateway returns the CellularGateway field value if set, zero value otherwise.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetCellularGateway() GetNetworkFirmwareUpgrades200ResponseProductsWireless {
	if o == nil || o.CellularGateway == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseProductsWireless
		return ret
	}
	return *o.CellularGateway
}

// GetCellularGatewayOk returns a tuple with the CellularGateway field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) GetCellularGatewayOk() (*GetNetworkFirmwareUpgrades200ResponseProductsWireless, bool) {
	if o == nil || o.CellularGateway == nil {
		return nil, false
	}
	return o.CellularGateway, true
}

// HasCellularGateway returns a boolean if a field has been set.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) HasCellularGateway() bool {
	if o != nil && o.CellularGateway != nil {
		return true
	}

	return false
}

// SetCellularGateway gets a reference to the given GetNetworkFirmwareUpgrades200ResponseProductsWireless and assigns it to the CellularGateway field.
func (o *GetNetworkFirmwareUpgrades200ResponseProducts) SetCellularGateway(v GetNetworkFirmwareUpgrades200ResponseProductsWireless) {
	o.CellularGateway = &v
}

func (o GetNetworkFirmwareUpgrades200ResponseProducts) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Wireless != nil {
		toSerialize["wireless"] = o.Wireless
	}
	if o.Switch != nil {
		toSerialize["switch"] = o.Switch
	}
	if o.Appliance != nil {
		toSerialize["appliance"] = o.Appliance
	}
	if o.Camera != nil {
		toSerialize["camera"] = o.Camera
	}
	if o.VmxHost != nil {
		toSerialize["vmxHost"] = o.VmxHost
	}
	if o.Environmental != nil {
		toSerialize["environmental"] = o.Environmental
	}
	if o.Sensor != nil {
		toSerialize["sensor"] = o.Sensor
	}
	if o.CellularGateway != nil {
		toSerialize["cellularGateway"] = o.CellularGateway
	}
	return json.Marshal(toSerialize)
}

type NullableGetNetworkFirmwareUpgrades200ResponseProducts struct {
	value *GetNetworkFirmwareUpgrades200ResponseProducts
	isSet bool
}

func (v NullableGetNetworkFirmwareUpgrades200ResponseProducts) Get() *GetNetworkFirmwareUpgrades200ResponseProducts {
	return v.value
}

func (v *NullableGetNetworkFirmwareUpgrades200ResponseProducts) Set(val *GetNetworkFirmwareUpgrades200ResponseProducts) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkFirmwareUpgrades200ResponseProducts) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkFirmwareUpgrades200ResponseProducts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkFirmwareUpgrades200ResponseProducts(val *GetNetworkFirmwareUpgrades200ResponseProducts) *NullableGetNetworkFirmwareUpgrades200ResponseProducts {
	return &NullableGetNetworkFirmwareUpgrades200ResponseProducts{value: val, isSet: true}
}

func (v NullableGetNetworkFirmwareUpgrades200ResponseProducts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkFirmwareUpgrades200ResponseProducts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


