/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 July, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.23.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meraki

import (
	"encoding/json"
	"time"
)

// GetNetworkSwitchDhcpV4ServersSeen200ResponseInner struct for GetNetworkSwitchDhcpV4ServersSeen200ResponseInner
type GetNetworkSwitchDhcpV4ServersSeen200ResponseInner struct {
	// Mac address of the DHCPv4 server.
	Mac *string `json:"mac,omitempty"`
	// Vlan id of the DHCPv4 server.
	Vlan *int32 `json:"vlan,omitempty"`
	Ipv4 *GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4 `json:"ipv4,omitempty"`
	// Client id of the DHCPv4 server if available.
	ClientId *string `json:"clientId,omitempty"`
	// Whether the DHCPv4 server is allowed or blocked. Always true for configured servers.
	IsAllowed *bool `json:"isAllowed,omitempty"`
	// Whether the DHCPv4 server is configured.
	IsConfigured *bool `json:"isConfigured,omitempty"`
	// Last time the DHCPv4 server was seen.
	LastSeenAt *time.Time `json:"lastSeenAt,omitempty"`
	LastAck *GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck `json:"lastAck,omitempty"`
	// Devices that saw the DHCPv4 server.
	SeenBy []GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner `json:"seenBy,omitempty"`
	// DHCPv4 server type. Can be a 'device', 'stack', or 'discovered' (i.e client).
	Type *string `json:"type,omitempty"`
	Device *GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice `json:"device,omitempty"`
	LastPacket *GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket `json:"lastPacket,omitempty"`
}

// NewGetNetworkSwitchDhcpV4ServersSeen200ResponseInner instantiates a new GetNetworkSwitchDhcpV4ServersSeen200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkSwitchDhcpV4ServersSeen200ResponseInner() *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner {
	this := GetNetworkSwitchDhcpV4ServersSeen200ResponseInner{}
	return &this
}

// NewGetNetworkSwitchDhcpV4ServersSeen200ResponseInnerWithDefaults instantiates a new GetNetworkSwitchDhcpV4ServersSeen200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkSwitchDhcpV4ServersSeen200ResponseInnerWithDefaults() *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner {
	this := GetNetworkSwitchDhcpV4ServersSeen200ResponseInner{}
	return &this
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetMac() string {
	if o == nil || o.Mac == nil {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetMacOk() (*string, bool) {
	if o == nil || o.Mac == nil {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasMac() bool {
	if o != nil && o.Mac != nil {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetMac(v string) {
	o.Mac = &v
}

// GetVlan returns the Vlan field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetVlan() int32 {
	if o == nil || o.Vlan == nil {
		var ret int32
		return ret
	}
	return *o.Vlan
}

// GetVlanOk returns a tuple with the Vlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetVlanOk() (*int32, bool) {
	if o == nil || o.Vlan == nil {
		return nil, false
	}
	return o.Vlan, true
}

// HasVlan returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasVlan() bool {
	if o != nil && o.Vlan != nil {
		return true
	}

	return false
}

// SetVlan gets a reference to the given int32 and assigns it to the Vlan field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetVlan(v int32) {
	o.Vlan = &v
}

// GetIpv4 returns the Ipv4 field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIpv4() GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4 {
	if o == nil || o.Ipv4 == nil {
		var ret GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4
		return ret
	}
	return *o.Ipv4
}

// GetIpv4Ok returns a tuple with the Ipv4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIpv4Ok() (*GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4, bool) {
	if o == nil || o.Ipv4 == nil {
		return nil, false
	}
	return o.Ipv4, true
}

// HasIpv4 returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasIpv4() bool {
	if o != nil && o.Ipv4 != nil {
		return true
	}

	return false
}

// SetIpv4 gets a reference to the given GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4 and assigns it to the Ipv4 field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetIpv4(v GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerIpv4) {
	o.Ipv4 = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetClientIdOk() (*string, bool) {
	if o == nil || o.ClientId == nil {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetClientId(v string) {
	o.ClientId = &v
}

// GetIsAllowed returns the IsAllowed field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIsAllowed() bool {
	if o == nil || o.IsAllowed == nil {
		var ret bool
		return ret
	}
	return *o.IsAllowed
}

// GetIsAllowedOk returns a tuple with the IsAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIsAllowedOk() (*bool, bool) {
	if o == nil || o.IsAllowed == nil {
		return nil, false
	}
	return o.IsAllowed, true
}

// HasIsAllowed returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasIsAllowed() bool {
	if o != nil && o.IsAllowed != nil {
		return true
	}

	return false
}

// SetIsAllowed gets a reference to the given bool and assigns it to the IsAllowed field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetIsAllowed(v bool) {
	o.IsAllowed = &v
}

// GetIsConfigured returns the IsConfigured field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIsConfigured() bool {
	if o == nil || o.IsConfigured == nil {
		var ret bool
		return ret
	}
	return *o.IsConfigured
}

// GetIsConfiguredOk returns a tuple with the IsConfigured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetIsConfiguredOk() (*bool, bool) {
	if o == nil || o.IsConfigured == nil {
		return nil, false
	}
	return o.IsConfigured, true
}

// HasIsConfigured returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasIsConfigured() bool {
	if o != nil && o.IsConfigured != nil {
		return true
	}

	return false
}

// SetIsConfigured gets a reference to the given bool and assigns it to the IsConfigured field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetIsConfigured(v bool) {
	o.IsConfigured = &v
}

// GetLastSeenAt returns the LastSeenAt field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastSeenAt() time.Time {
	if o == nil || o.LastSeenAt == nil {
		var ret time.Time
		return ret
	}
	return *o.LastSeenAt
}

// GetLastSeenAtOk returns a tuple with the LastSeenAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastSeenAtOk() (*time.Time, bool) {
	if o == nil || o.LastSeenAt == nil {
		return nil, false
	}
	return o.LastSeenAt, true
}

// HasLastSeenAt returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasLastSeenAt() bool {
	if o != nil && o.LastSeenAt != nil {
		return true
	}

	return false
}

// SetLastSeenAt gets a reference to the given time.Time and assigns it to the LastSeenAt field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetLastSeenAt(v time.Time) {
	o.LastSeenAt = &v
}

// GetLastAck returns the LastAck field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastAck() GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck {
	if o == nil || o.LastAck == nil {
		var ret GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck
		return ret
	}
	return *o.LastAck
}

// GetLastAckOk returns a tuple with the LastAck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastAckOk() (*GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck, bool) {
	if o == nil || o.LastAck == nil {
		return nil, false
	}
	return o.LastAck, true
}

// HasLastAck returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasLastAck() bool {
	if o != nil && o.LastAck != nil {
		return true
	}

	return false
}

// SetLastAck gets a reference to the given GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck and assigns it to the LastAck field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetLastAck(v GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastAck) {
	o.LastAck = &v
}

// GetSeenBy returns the SeenBy field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetSeenBy() []GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner {
	if o == nil || o.SeenBy == nil {
		var ret []GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner
		return ret
	}
	return o.SeenBy
}

// GetSeenByOk returns a tuple with the SeenBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetSeenByOk() ([]GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner, bool) {
	if o == nil || o.SeenBy == nil {
		return nil, false
	}
	return o.SeenBy, true
}

// HasSeenBy returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasSeenBy() bool {
	if o != nil && o.SeenBy != nil {
		return true
	}

	return false
}

// SetSeenBy gets a reference to the given []GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner and assigns it to the SeenBy field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetSeenBy(v []GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerSeenByInner) {
	o.SeenBy = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetType(v string) {
	o.Type = &v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetDevice() GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice {
	if o == nil || o.Device == nil {
		var ret GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetDeviceOk() (*GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice, bool) {
	if o == nil || o.Device == nil {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasDevice() bool {
	if o != nil && o.Device != nil {
		return true
	}

	return false
}

// SetDevice gets a reference to the given GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice and assigns it to the Device field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetDevice(v GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerDevice) {
	o.Device = &v
}

// GetLastPacket returns the LastPacket field value if set, zero value otherwise.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastPacket() GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket {
	if o == nil || o.LastPacket == nil {
		var ret GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket
		return ret
	}
	return *o.LastPacket
}

// GetLastPacketOk returns a tuple with the LastPacket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) GetLastPacketOk() (*GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket, bool) {
	if o == nil || o.LastPacket == nil {
		return nil, false
	}
	return o.LastPacket, true
}

// HasLastPacket returns a boolean if a field has been set.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) HasLastPacket() bool {
	if o != nil && o.LastPacket != nil {
		return true
	}

	return false
}

// SetLastPacket gets a reference to the given GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket and assigns it to the LastPacket field.
func (o *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) SetLastPacket(v GetNetworkSwitchDhcpV4ServersSeen200ResponseInnerLastPacket) {
	o.LastPacket = &v
}

func (o GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Mac != nil {
		toSerialize["mac"] = o.Mac
	}
	if o.Vlan != nil {
		toSerialize["vlan"] = o.Vlan
	}
	if o.Ipv4 != nil {
		toSerialize["ipv4"] = o.Ipv4
	}
	if o.ClientId != nil {
		toSerialize["clientId"] = o.ClientId
	}
	if o.IsAllowed != nil {
		toSerialize["isAllowed"] = o.IsAllowed
	}
	if o.IsConfigured != nil {
		toSerialize["isConfigured"] = o.IsConfigured
	}
	if o.LastSeenAt != nil {
		toSerialize["lastSeenAt"] = o.LastSeenAt
	}
	if o.LastAck != nil {
		toSerialize["lastAck"] = o.LastAck
	}
	if o.SeenBy != nil {
		toSerialize["seenBy"] = o.SeenBy
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Device != nil {
		toSerialize["device"] = o.Device
	}
	if o.LastPacket != nil {
		toSerialize["lastPacket"] = o.LastPacket
	}
	return json.Marshal(toSerialize)
}

type NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner struct {
	value *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner
	isSet bool
}

func (v NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) Get() *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner {
	return v.value
}

func (v *NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) Set(val *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner(val *GetNetworkSwitchDhcpV4ServersSeen200ResponseInner) *NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner {
	return &NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner{value: val, isSet: true}
}

func (v NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkSwitchDhcpV4ServersSeen200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


