/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 July, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.23.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meraki

import (
	"encoding/json"
)

// UpdateNetworkFirmwareUpgradesRequest struct for UpdateNetworkFirmwareUpgradesRequest
type UpdateNetworkFirmwareUpgradesRequest struct {
	UpgradeWindow *GetNetworkFirmwareUpgrades200ResponseUpgradeWindow `json:"upgradeWindow,omitempty"`
	// The timezone for the network
	Timezone *string `json:"timezone,omitempty"`
	Products *UpdateNetworkFirmwareUpgradesRequestProducts `json:"products,omitempty"`
}

// NewUpdateNetworkFirmwareUpgradesRequest instantiates a new UpdateNetworkFirmwareUpgradesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNetworkFirmwareUpgradesRequest() *UpdateNetworkFirmwareUpgradesRequest {
	this := UpdateNetworkFirmwareUpgradesRequest{}
	return &this
}

// NewUpdateNetworkFirmwareUpgradesRequestWithDefaults instantiates a new UpdateNetworkFirmwareUpgradesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkFirmwareUpgradesRequestWithDefaults() *UpdateNetworkFirmwareUpgradesRequest {
	this := UpdateNetworkFirmwareUpgradesRequest{}
	return &this
}

// GetUpgradeWindow returns the UpgradeWindow field value if set, zero value otherwise.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetUpgradeWindow() GetNetworkFirmwareUpgrades200ResponseUpgradeWindow {
	if o == nil || o.UpgradeWindow == nil {
		var ret GetNetworkFirmwareUpgrades200ResponseUpgradeWindow
		return ret
	}
	return *o.UpgradeWindow
}

// GetUpgradeWindowOk returns a tuple with the UpgradeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetUpgradeWindowOk() (*GetNetworkFirmwareUpgrades200ResponseUpgradeWindow, bool) {
	if o == nil || o.UpgradeWindow == nil {
		return nil, false
	}
	return o.UpgradeWindow, true
}

// HasUpgradeWindow returns a boolean if a field has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) HasUpgradeWindow() bool {
	if o != nil && o.UpgradeWindow != nil {
		return true
	}

	return false
}

// SetUpgradeWindow gets a reference to the given GetNetworkFirmwareUpgrades200ResponseUpgradeWindow and assigns it to the UpgradeWindow field.
func (o *UpdateNetworkFirmwareUpgradesRequest) SetUpgradeWindow(v GetNetworkFirmwareUpgrades200ResponseUpgradeWindow) {
	o.UpgradeWindow = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetTimezone() string {
	if o == nil || o.Timezone == nil {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetTimezoneOk() (*string, bool) {
	if o == nil || o.Timezone == nil {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) HasTimezone() bool {
	if o != nil && o.Timezone != nil {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *UpdateNetworkFirmwareUpgradesRequest) SetTimezone(v string) {
	o.Timezone = &v
}

// GetProducts returns the Products field value if set, zero value otherwise.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetProducts() UpdateNetworkFirmwareUpgradesRequestProducts {
	if o == nil || o.Products == nil {
		var ret UpdateNetworkFirmwareUpgradesRequestProducts
		return ret
	}
	return *o.Products
}

// GetProductsOk returns a tuple with the Products field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) GetProductsOk() (*UpdateNetworkFirmwareUpgradesRequestProducts, bool) {
	if o == nil || o.Products == nil {
		return nil, false
	}
	return o.Products, true
}

// HasProducts returns a boolean if a field has been set.
func (o *UpdateNetworkFirmwareUpgradesRequest) HasProducts() bool {
	if o != nil && o.Products != nil {
		return true
	}

	return false
}

// SetProducts gets a reference to the given UpdateNetworkFirmwareUpgradesRequestProducts and assigns it to the Products field.
func (o *UpdateNetworkFirmwareUpgradesRequest) SetProducts(v UpdateNetworkFirmwareUpgradesRequestProducts) {
	o.Products = &v
}

func (o UpdateNetworkFirmwareUpgradesRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UpgradeWindow != nil {
		toSerialize["upgradeWindow"] = o.UpgradeWindow
	}
	if o.Timezone != nil {
		toSerialize["timezone"] = o.Timezone
	}
	if o.Products != nil {
		toSerialize["products"] = o.Products
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateNetworkFirmwareUpgradesRequest struct {
	value *UpdateNetworkFirmwareUpgradesRequest
	isSet bool
}

func (v NullableUpdateNetworkFirmwareUpgradesRequest) Get() *UpdateNetworkFirmwareUpgradesRequest {
	return v.value
}

func (v *NullableUpdateNetworkFirmwareUpgradesRequest) Set(val *UpdateNetworkFirmwareUpgradesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkFirmwareUpgradesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkFirmwareUpgradesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkFirmwareUpgradesRequest(val *UpdateNetworkFirmwareUpgradesRequest) *NullableUpdateNetworkFirmwareUpgradesRequest {
	return &NullableUpdateNetworkFirmwareUpgradesRequest{value: val, isSet: true}
}

func (v NullableUpdateNetworkFirmwareUpgradesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkFirmwareUpgradesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


