/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 July, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.23.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meraki

import (
	"encoding/json"
)

// CreateNetworkWirelessRfProfile201ResponsePerSsidSettings Per-SSID radio settings by number.
type CreateNetworkWirelessRfProfile201ResponsePerSsidSettings struct {
	Var0 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0 `json:"0,omitempty"`
	Var1 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1 `json:"1,omitempty"`
	Var2 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2 `json:"2,omitempty"`
	Var3 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3 `json:"3,omitempty"`
	Var4 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4 `json:"4,omitempty"`
	Var5 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5 `json:"5,omitempty"`
	Var6 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6 `json:"6,omitempty"`
	Var7 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7 `json:"7,omitempty"`
	Var8 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8 `json:"8,omitempty"`
	Var9 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9 `json:"9,omitempty"`
	Var10 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10 `json:"10,omitempty"`
	Var11 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11 `json:"11,omitempty"`
	Var12 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12 `json:"12,omitempty"`
	Var13 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13 `json:"13,omitempty"`
	Var14 *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14 `json:"14,omitempty"`
}

// NewCreateNetworkWirelessRfProfile201ResponsePerSsidSettings instantiates a new CreateNetworkWirelessRfProfile201ResponsePerSsidSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNetworkWirelessRfProfile201ResponsePerSsidSettings() *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings {
	this := CreateNetworkWirelessRfProfile201ResponsePerSsidSettings{}
	return &this
}

// NewCreateNetworkWirelessRfProfile201ResponsePerSsidSettingsWithDefaults instantiates a new CreateNetworkWirelessRfProfile201ResponsePerSsidSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNetworkWirelessRfProfile201ResponsePerSsidSettingsWithDefaults() *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings {
	this := CreateNetworkWirelessRfProfile201ResponsePerSsidSettings{}
	return &this
}

// GetVar0 returns the Var0 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar0() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0 {
	if o == nil || o.Var0 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0
		return ret
	}
	return *o.Var0
}

// GetVar0Ok returns a tuple with the Var0 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar0Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0, bool) {
	if o == nil || o.Var0 == nil {
		return nil, false
	}
	return o.Var0, true
}

// HasVar0 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar0() bool {
	if o != nil && o.Var0 != nil {
		return true
	}

	return false
}

// SetVar0 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0 and assigns it to the Var0 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar0(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings0) {
	o.Var0 = &v
}

// GetVar1 returns the Var1 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar1() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1 {
	if o == nil || o.Var1 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1
		return ret
	}
	return *o.Var1
}

// GetVar1Ok returns a tuple with the Var1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar1Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1, bool) {
	if o == nil || o.Var1 == nil {
		return nil, false
	}
	return o.Var1, true
}

// HasVar1 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar1() bool {
	if o != nil && o.Var1 != nil {
		return true
	}

	return false
}

// SetVar1 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1 and assigns it to the Var1 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar1(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings1) {
	o.Var1 = &v
}

// GetVar2 returns the Var2 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar2() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2 {
	if o == nil || o.Var2 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2
		return ret
	}
	return *o.Var2
}

// GetVar2Ok returns a tuple with the Var2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar2Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2, bool) {
	if o == nil || o.Var2 == nil {
		return nil, false
	}
	return o.Var2, true
}

// HasVar2 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar2() bool {
	if o != nil && o.Var2 != nil {
		return true
	}

	return false
}

// SetVar2 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2 and assigns it to the Var2 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar2(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings2) {
	o.Var2 = &v
}

// GetVar3 returns the Var3 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar3() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3 {
	if o == nil || o.Var3 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3
		return ret
	}
	return *o.Var3
}

// GetVar3Ok returns a tuple with the Var3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar3Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3, bool) {
	if o == nil || o.Var3 == nil {
		return nil, false
	}
	return o.Var3, true
}

// HasVar3 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar3() bool {
	if o != nil && o.Var3 != nil {
		return true
	}

	return false
}

// SetVar3 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3 and assigns it to the Var3 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar3(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings3) {
	o.Var3 = &v
}

// GetVar4 returns the Var4 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar4() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4 {
	if o == nil || o.Var4 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4
		return ret
	}
	return *o.Var4
}

// GetVar4Ok returns a tuple with the Var4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar4Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4, bool) {
	if o == nil || o.Var4 == nil {
		return nil, false
	}
	return o.Var4, true
}

// HasVar4 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar4() bool {
	if o != nil && o.Var4 != nil {
		return true
	}

	return false
}

// SetVar4 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4 and assigns it to the Var4 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar4(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings4) {
	o.Var4 = &v
}

// GetVar5 returns the Var5 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar5() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5 {
	if o == nil || o.Var5 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5
		return ret
	}
	return *o.Var5
}

// GetVar5Ok returns a tuple with the Var5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar5Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5, bool) {
	if o == nil || o.Var5 == nil {
		return nil, false
	}
	return o.Var5, true
}

// HasVar5 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar5() bool {
	if o != nil && o.Var5 != nil {
		return true
	}

	return false
}

// SetVar5 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5 and assigns it to the Var5 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar5(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings5) {
	o.Var5 = &v
}

// GetVar6 returns the Var6 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar6() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6 {
	if o == nil || o.Var6 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6
		return ret
	}
	return *o.Var6
}

// GetVar6Ok returns a tuple with the Var6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar6Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6, bool) {
	if o == nil || o.Var6 == nil {
		return nil, false
	}
	return o.Var6, true
}

// HasVar6 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar6() bool {
	if o != nil && o.Var6 != nil {
		return true
	}

	return false
}

// SetVar6 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6 and assigns it to the Var6 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar6(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings6) {
	o.Var6 = &v
}

// GetVar7 returns the Var7 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar7() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7 {
	if o == nil || o.Var7 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7
		return ret
	}
	return *o.Var7
}

// GetVar7Ok returns a tuple with the Var7 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar7Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7, bool) {
	if o == nil || o.Var7 == nil {
		return nil, false
	}
	return o.Var7, true
}

// HasVar7 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar7() bool {
	if o != nil && o.Var7 != nil {
		return true
	}

	return false
}

// SetVar7 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7 and assigns it to the Var7 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar7(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings7) {
	o.Var7 = &v
}

// GetVar8 returns the Var8 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar8() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8 {
	if o == nil || o.Var8 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8
		return ret
	}
	return *o.Var8
}

// GetVar8Ok returns a tuple with the Var8 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar8Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8, bool) {
	if o == nil || o.Var8 == nil {
		return nil, false
	}
	return o.Var8, true
}

// HasVar8 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar8() bool {
	if o != nil && o.Var8 != nil {
		return true
	}

	return false
}

// SetVar8 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8 and assigns it to the Var8 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar8(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings8) {
	o.Var8 = &v
}

// GetVar9 returns the Var9 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar9() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9 {
	if o == nil || o.Var9 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9
		return ret
	}
	return *o.Var9
}

// GetVar9Ok returns a tuple with the Var9 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar9Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9, bool) {
	if o == nil || o.Var9 == nil {
		return nil, false
	}
	return o.Var9, true
}

// HasVar9 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar9() bool {
	if o != nil && o.Var9 != nil {
		return true
	}

	return false
}

// SetVar9 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9 and assigns it to the Var9 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar9(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings9) {
	o.Var9 = &v
}

// GetVar10 returns the Var10 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar10() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10 {
	if o == nil || o.Var10 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10
		return ret
	}
	return *o.Var10
}

// GetVar10Ok returns a tuple with the Var10 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar10Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10, bool) {
	if o == nil || o.Var10 == nil {
		return nil, false
	}
	return o.Var10, true
}

// HasVar10 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar10() bool {
	if o != nil && o.Var10 != nil {
		return true
	}

	return false
}

// SetVar10 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10 and assigns it to the Var10 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar10(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings10) {
	o.Var10 = &v
}

// GetVar11 returns the Var11 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar11() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11 {
	if o == nil || o.Var11 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11
		return ret
	}
	return *o.Var11
}

// GetVar11Ok returns a tuple with the Var11 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar11Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11, bool) {
	if o == nil || o.Var11 == nil {
		return nil, false
	}
	return o.Var11, true
}

// HasVar11 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar11() bool {
	if o != nil && o.Var11 != nil {
		return true
	}

	return false
}

// SetVar11 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11 and assigns it to the Var11 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar11(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings11) {
	o.Var11 = &v
}

// GetVar12 returns the Var12 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar12() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12 {
	if o == nil || o.Var12 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12
		return ret
	}
	return *o.Var12
}

// GetVar12Ok returns a tuple with the Var12 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar12Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12, bool) {
	if o == nil || o.Var12 == nil {
		return nil, false
	}
	return o.Var12, true
}

// HasVar12 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar12() bool {
	if o != nil && o.Var12 != nil {
		return true
	}

	return false
}

// SetVar12 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12 and assigns it to the Var12 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar12(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings12) {
	o.Var12 = &v
}

// GetVar13 returns the Var13 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar13() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13 {
	if o == nil || o.Var13 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13
		return ret
	}
	return *o.Var13
}

// GetVar13Ok returns a tuple with the Var13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar13Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13, bool) {
	if o == nil || o.Var13 == nil {
		return nil, false
	}
	return o.Var13, true
}

// HasVar13 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar13() bool {
	if o != nil && o.Var13 != nil {
		return true
	}

	return false
}

// SetVar13 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13 and assigns it to the Var13 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar13(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings13) {
	o.Var13 = &v
}

// GetVar14 returns the Var14 field value if set, zero value otherwise.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar14() CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14 {
	if o == nil || o.Var14 == nil {
		var ret CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14
		return ret
	}
	return *o.Var14
}

// GetVar14Ok returns a tuple with the Var14 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) GetVar14Ok() (*CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14, bool) {
	if o == nil || o.Var14 == nil {
		return nil, false
	}
	return o.Var14, true
}

// HasVar14 returns a boolean if a field has been set.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) HasVar14() bool {
	if o != nil && o.Var14 != nil {
		return true
	}

	return false
}

// SetVar14 gets a reference to the given CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14 and assigns it to the Var14 field.
func (o *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) SetVar14(v CreateNetworkWirelessRfProfile201ResponsePerSsidSettings14) {
	o.Var14 = &v
}

func (o CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Var0 != nil {
		toSerialize["0"] = o.Var0
	}
	if o.Var1 != nil {
		toSerialize["1"] = o.Var1
	}
	if o.Var2 != nil {
		toSerialize["2"] = o.Var2
	}
	if o.Var3 != nil {
		toSerialize["3"] = o.Var3
	}
	if o.Var4 != nil {
		toSerialize["4"] = o.Var4
	}
	if o.Var5 != nil {
		toSerialize["5"] = o.Var5
	}
	if o.Var6 != nil {
		toSerialize["6"] = o.Var6
	}
	if o.Var7 != nil {
		toSerialize["7"] = o.Var7
	}
	if o.Var8 != nil {
		toSerialize["8"] = o.Var8
	}
	if o.Var9 != nil {
		toSerialize["9"] = o.Var9
	}
	if o.Var10 != nil {
		toSerialize["10"] = o.Var10
	}
	if o.Var11 != nil {
		toSerialize["11"] = o.Var11
	}
	if o.Var12 != nil {
		toSerialize["12"] = o.Var12
	}
	if o.Var13 != nil {
		toSerialize["13"] = o.Var13
	}
	if o.Var14 != nil {
		toSerialize["14"] = o.Var14
	}
	return json.Marshal(toSerialize)
}

type NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings struct {
	value *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings
	isSet bool
}

func (v NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) Get() *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings {
	return v.value
}

func (v *NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) Set(val *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings(val *CreateNetworkWirelessRfProfile201ResponsePerSsidSettings) *NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings {
	return &NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings{value: val, isSet: true}
}

func (v NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNetworkWirelessRfProfile201ResponsePerSsidSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


