/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 06 July, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.23.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package meraki

import (
	"encoding/json"
)

// UpdateNetworkApplianceVlanRequest struct for UpdateNetworkApplianceVlanRequest
type UpdateNetworkApplianceVlanRequest struct {
	// The name of the VLAN
	Name *string `json:"name,omitempty"`
	// The subnet of the VLAN
	Subnet *string `json:"subnet,omitempty"`
	// The local IP of the appliance on the VLAN
	ApplianceIp *string `json:"applianceIp,omitempty"`
	// The id of the desired group policy to apply to the VLAN
	GroupPolicyId *string `json:"groupPolicyId,omitempty"`
	// The translated VPN subnet if VPN and VPN subnet translation are enabled on the VLAN
	VpnNatSubnet *string `json:"vpnNatSubnet,omitempty"`
	// The appliance's handling of DHCP requests on this VLAN. One of: 'Run a DHCP server', 'Relay DHCP to another server' or 'Do not respond to DHCP requests'
	DhcpHandling *string `json:"dhcpHandling,omitempty"`
	// The IPs of the DHCP servers that DHCP requests should be relayed to
	DhcpRelayServerIps []string `json:"dhcpRelayServerIps,omitempty"`
	// The term of DHCP leases if the appliance is running a DHCP server on this VLAN. One of: '30 minutes', '1 hour', '4 hours', '12 hours', '1 day' or '1 week'
	DhcpLeaseTime *string `json:"dhcpLeaseTime,omitempty"`
	// Use DHCP boot options specified in other properties
	DhcpBootOptionsEnabled *bool `json:"dhcpBootOptionsEnabled,omitempty"`
	// DHCP boot option to direct boot clients to the server to load the boot file from
	DhcpBootNextServer *string `json:"dhcpBootNextServer,omitempty"`
	// DHCP boot option for boot filename
	DhcpBootFilename *string `json:"dhcpBootFilename,omitempty"`
	// The DHCP fixed IP assignments on the VLAN. This should be an object that contains mappings from MAC addresses to objects that themselves each contain \"ip\" and \"name\" string fields. See the sample request/response for more details.
	FixedIpAssignments map[string]interface{} `json:"fixedIpAssignments,omitempty"`
	// The DHCP reserved IP ranges on the VLAN
	ReservedIpRanges []UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner `json:"reservedIpRanges,omitempty"`
	// The DNS nameservers used for DHCP responses, either \"upstream_dns\", \"google_dns\", \"opendns\", or a newline seperated string of IP addresses or domain names
	DnsNameservers *string `json:"dnsNameservers,omitempty"`
	// The list of DHCP options that will be included in DHCP responses. Each object in the list should have \"code\", \"type\", and \"value\" properties.
	DhcpOptions []UpdateNetworkApplianceVlanRequestDhcpOptionsInner `json:"dhcpOptions,omitempty"`
	// Type of subnetting of the VLAN. Applicable only for template network.
	TemplateVlanType *string `json:"templateVlanType,omitempty"`
	// CIDR of the pool of subnets. Applicable only for template network. Each network bound to the template will automatically pick a subnet from this pool to build its own VLAN.
	Cidr *string `json:"cidr,omitempty"`
	// Mask used for the subnet of all bound to the template networks. Applicable only for template network.
	Mask *int32 `json:"mask,omitempty"`
}

// NewUpdateNetworkApplianceVlanRequest instantiates a new UpdateNetworkApplianceVlanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNetworkApplianceVlanRequest() *UpdateNetworkApplianceVlanRequest {
	this := UpdateNetworkApplianceVlanRequest{}
	return &this
}

// NewUpdateNetworkApplianceVlanRequestWithDefaults instantiates a new UpdateNetworkApplianceVlanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNetworkApplianceVlanRequestWithDefaults() *UpdateNetworkApplianceVlanRequest {
	this := UpdateNetworkApplianceVlanRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateNetworkApplianceVlanRequest) SetName(v string) {
	o.Name = &v
}

// GetSubnet returns the Subnet field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetSubnet() string {
	if o == nil || o.Subnet == nil {
		var ret string
		return ret
	}
	return *o.Subnet
}

// GetSubnetOk returns a tuple with the Subnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetSubnetOk() (*string, bool) {
	if o == nil || o.Subnet == nil {
		return nil, false
	}
	return o.Subnet, true
}

// HasSubnet returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasSubnet() bool {
	if o != nil && o.Subnet != nil {
		return true
	}

	return false
}

// SetSubnet gets a reference to the given string and assigns it to the Subnet field.
func (o *UpdateNetworkApplianceVlanRequest) SetSubnet(v string) {
	o.Subnet = &v
}

// GetApplianceIp returns the ApplianceIp field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetApplianceIp() string {
	if o == nil || o.ApplianceIp == nil {
		var ret string
		return ret
	}
	return *o.ApplianceIp
}

// GetApplianceIpOk returns a tuple with the ApplianceIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetApplianceIpOk() (*string, bool) {
	if o == nil || o.ApplianceIp == nil {
		return nil, false
	}
	return o.ApplianceIp, true
}

// HasApplianceIp returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasApplianceIp() bool {
	if o != nil && o.ApplianceIp != nil {
		return true
	}

	return false
}

// SetApplianceIp gets a reference to the given string and assigns it to the ApplianceIp field.
func (o *UpdateNetworkApplianceVlanRequest) SetApplianceIp(v string) {
	o.ApplianceIp = &v
}

// GetGroupPolicyId returns the GroupPolicyId field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetGroupPolicyId() string {
	if o == nil || o.GroupPolicyId == nil {
		var ret string
		return ret
	}
	return *o.GroupPolicyId
}

// GetGroupPolicyIdOk returns a tuple with the GroupPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetGroupPolicyIdOk() (*string, bool) {
	if o == nil || o.GroupPolicyId == nil {
		return nil, false
	}
	return o.GroupPolicyId, true
}

// HasGroupPolicyId returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasGroupPolicyId() bool {
	if o != nil && o.GroupPolicyId != nil {
		return true
	}

	return false
}

// SetGroupPolicyId gets a reference to the given string and assigns it to the GroupPolicyId field.
func (o *UpdateNetworkApplianceVlanRequest) SetGroupPolicyId(v string) {
	o.GroupPolicyId = &v
}

// GetVpnNatSubnet returns the VpnNatSubnet field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetVpnNatSubnet() string {
	if o == nil || o.VpnNatSubnet == nil {
		var ret string
		return ret
	}
	return *o.VpnNatSubnet
}

// GetVpnNatSubnetOk returns a tuple with the VpnNatSubnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetVpnNatSubnetOk() (*string, bool) {
	if o == nil || o.VpnNatSubnet == nil {
		return nil, false
	}
	return o.VpnNatSubnet, true
}

// HasVpnNatSubnet returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasVpnNatSubnet() bool {
	if o != nil && o.VpnNatSubnet != nil {
		return true
	}

	return false
}

// SetVpnNatSubnet gets a reference to the given string and assigns it to the VpnNatSubnet field.
func (o *UpdateNetworkApplianceVlanRequest) SetVpnNatSubnet(v string) {
	o.VpnNatSubnet = &v
}

// GetDhcpHandling returns the DhcpHandling field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpHandling() string {
	if o == nil || o.DhcpHandling == nil {
		var ret string
		return ret
	}
	return *o.DhcpHandling
}

// GetDhcpHandlingOk returns a tuple with the DhcpHandling field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpHandlingOk() (*string, bool) {
	if o == nil || o.DhcpHandling == nil {
		return nil, false
	}
	return o.DhcpHandling, true
}

// HasDhcpHandling returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpHandling() bool {
	if o != nil && o.DhcpHandling != nil {
		return true
	}

	return false
}

// SetDhcpHandling gets a reference to the given string and assigns it to the DhcpHandling field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpHandling(v string) {
	o.DhcpHandling = &v
}

// GetDhcpRelayServerIps returns the DhcpRelayServerIps field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpRelayServerIps() []string {
	if o == nil || o.DhcpRelayServerIps == nil {
		var ret []string
		return ret
	}
	return o.DhcpRelayServerIps
}

// GetDhcpRelayServerIpsOk returns a tuple with the DhcpRelayServerIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpRelayServerIpsOk() ([]string, bool) {
	if o == nil || o.DhcpRelayServerIps == nil {
		return nil, false
	}
	return o.DhcpRelayServerIps, true
}

// HasDhcpRelayServerIps returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpRelayServerIps() bool {
	if o != nil && o.DhcpRelayServerIps != nil {
		return true
	}

	return false
}

// SetDhcpRelayServerIps gets a reference to the given []string and assigns it to the DhcpRelayServerIps field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpRelayServerIps(v []string) {
	o.DhcpRelayServerIps = v
}

// GetDhcpLeaseTime returns the DhcpLeaseTime field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpLeaseTime() string {
	if o == nil || o.DhcpLeaseTime == nil {
		var ret string
		return ret
	}
	return *o.DhcpLeaseTime
}

// GetDhcpLeaseTimeOk returns a tuple with the DhcpLeaseTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpLeaseTimeOk() (*string, bool) {
	if o == nil || o.DhcpLeaseTime == nil {
		return nil, false
	}
	return o.DhcpLeaseTime, true
}

// HasDhcpLeaseTime returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpLeaseTime() bool {
	if o != nil && o.DhcpLeaseTime != nil {
		return true
	}

	return false
}

// SetDhcpLeaseTime gets a reference to the given string and assigns it to the DhcpLeaseTime field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpLeaseTime(v string) {
	o.DhcpLeaseTime = &v
}

// GetDhcpBootOptionsEnabled returns the DhcpBootOptionsEnabled field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootOptionsEnabled() bool {
	if o == nil || o.DhcpBootOptionsEnabled == nil {
		var ret bool
		return ret
	}
	return *o.DhcpBootOptionsEnabled
}

// GetDhcpBootOptionsEnabledOk returns a tuple with the DhcpBootOptionsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootOptionsEnabledOk() (*bool, bool) {
	if o == nil || o.DhcpBootOptionsEnabled == nil {
		return nil, false
	}
	return o.DhcpBootOptionsEnabled, true
}

// HasDhcpBootOptionsEnabled returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpBootOptionsEnabled() bool {
	if o != nil && o.DhcpBootOptionsEnabled != nil {
		return true
	}

	return false
}

// SetDhcpBootOptionsEnabled gets a reference to the given bool and assigns it to the DhcpBootOptionsEnabled field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpBootOptionsEnabled(v bool) {
	o.DhcpBootOptionsEnabled = &v
}

// GetDhcpBootNextServer returns the DhcpBootNextServer field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootNextServer() string {
	if o == nil || o.DhcpBootNextServer == nil {
		var ret string
		return ret
	}
	return *o.DhcpBootNextServer
}

// GetDhcpBootNextServerOk returns a tuple with the DhcpBootNextServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootNextServerOk() (*string, bool) {
	if o == nil || o.DhcpBootNextServer == nil {
		return nil, false
	}
	return o.DhcpBootNextServer, true
}

// HasDhcpBootNextServer returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpBootNextServer() bool {
	if o != nil && o.DhcpBootNextServer != nil {
		return true
	}

	return false
}

// SetDhcpBootNextServer gets a reference to the given string and assigns it to the DhcpBootNextServer field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpBootNextServer(v string) {
	o.DhcpBootNextServer = &v
}

// GetDhcpBootFilename returns the DhcpBootFilename field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootFilename() string {
	if o == nil || o.DhcpBootFilename == nil {
		var ret string
		return ret
	}
	return *o.DhcpBootFilename
}

// GetDhcpBootFilenameOk returns a tuple with the DhcpBootFilename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpBootFilenameOk() (*string, bool) {
	if o == nil || o.DhcpBootFilename == nil {
		return nil, false
	}
	return o.DhcpBootFilename, true
}

// HasDhcpBootFilename returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpBootFilename() bool {
	if o != nil && o.DhcpBootFilename != nil {
		return true
	}

	return false
}

// SetDhcpBootFilename gets a reference to the given string and assigns it to the DhcpBootFilename field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpBootFilename(v string) {
	o.DhcpBootFilename = &v
}

// GetFixedIpAssignments returns the FixedIpAssignments field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetFixedIpAssignments() map[string]interface{} {
	if o == nil || o.FixedIpAssignments == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.FixedIpAssignments
}

// GetFixedIpAssignmentsOk returns a tuple with the FixedIpAssignments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetFixedIpAssignmentsOk() (map[string]interface{}, bool) {
	if o == nil || o.FixedIpAssignments == nil {
		return nil, false
	}
	return o.FixedIpAssignments, true
}

// HasFixedIpAssignments returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasFixedIpAssignments() bool {
	if o != nil && o.FixedIpAssignments != nil {
		return true
	}

	return false
}

// SetFixedIpAssignments gets a reference to the given map[string]interface{} and assigns it to the FixedIpAssignments field.
func (o *UpdateNetworkApplianceVlanRequest) SetFixedIpAssignments(v map[string]interface{}) {
	o.FixedIpAssignments = v
}

// GetReservedIpRanges returns the ReservedIpRanges field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetReservedIpRanges() []UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner {
	if o == nil || o.ReservedIpRanges == nil {
		var ret []UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner
		return ret
	}
	return o.ReservedIpRanges
}

// GetReservedIpRangesOk returns a tuple with the ReservedIpRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetReservedIpRangesOk() ([]UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner, bool) {
	if o == nil || o.ReservedIpRanges == nil {
		return nil, false
	}
	return o.ReservedIpRanges, true
}

// HasReservedIpRanges returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasReservedIpRanges() bool {
	if o != nil && o.ReservedIpRanges != nil {
		return true
	}

	return false
}

// SetReservedIpRanges gets a reference to the given []UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner and assigns it to the ReservedIpRanges field.
func (o *UpdateNetworkApplianceVlanRequest) SetReservedIpRanges(v []UpdateNetworkApplianceStaticRouteRequestReservedIpRangesInner) {
	o.ReservedIpRanges = v
}

// GetDnsNameservers returns the DnsNameservers field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDnsNameservers() string {
	if o == nil || o.DnsNameservers == nil {
		var ret string
		return ret
	}
	return *o.DnsNameservers
}

// GetDnsNameserversOk returns a tuple with the DnsNameservers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDnsNameserversOk() (*string, bool) {
	if o == nil || o.DnsNameservers == nil {
		return nil, false
	}
	return o.DnsNameservers, true
}

// HasDnsNameservers returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDnsNameservers() bool {
	if o != nil && o.DnsNameservers != nil {
		return true
	}

	return false
}

// SetDnsNameservers gets a reference to the given string and assigns it to the DnsNameservers field.
func (o *UpdateNetworkApplianceVlanRequest) SetDnsNameservers(v string) {
	o.DnsNameservers = &v
}

// GetDhcpOptions returns the DhcpOptions field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpOptions() []UpdateNetworkApplianceVlanRequestDhcpOptionsInner {
	if o == nil || o.DhcpOptions == nil {
		var ret []UpdateNetworkApplianceVlanRequestDhcpOptionsInner
		return ret
	}
	return o.DhcpOptions
}

// GetDhcpOptionsOk returns a tuple with the DhcpOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetDhcpOptionsOk() ([]UpdateNetworkApplianceVlanRequestDhcpOptionsInner, bool) {
	if o == nil || o.DhcpOptions == nil {
		return nil, false
	}
	return o.DhcpOptions, true
}

// HasDhcpOptions returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasDhcpOptions() bool {
	if o != nil && o.DhcpOptions != nil {
		return true
	}

	return false
}

// SetDhcpOptions gets a reference to the given []UpdateNetworkApplianceVlanRequestDhcpOptionsInner and assigns it to the DhcpOptions field.
func (o *UpdateNetworkApplianceVlanRequest) SetDhcpOptions(v []UpdateNetworkApplianceVlanRequestDhcpOptionsInner) {
	o.DhcpOptions = v
}

// GetTemplateVlanType returns the TemplateVlanType field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetTemplateVlanType() string {
	if o == nil || o.TemplateVlanType == nil {
		var ret string
		return ret
	}
	return *o.TemplateVlanType
}

// GetTemplateVlanTypeOk returns a tuple with the TemplateVlanType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetTemplateVlanTypeOk() (*string, bool) {
	if o == nil || o.TemplateVlanType == nil {
		return nil, false
	}
	return o.TemplateVlanType, true
}

// HasTemplateVlanType returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasTemplateVlanType() bool {
	if o != nil && o.TemplateVlanType != nil {
		return true
	}

	return false
}

// SetTemplateVlanType gets a reference to the given string and assigns it to the TemplateVlanType field.
func (o *UpdateNetworkApplianceVlanRequest) SetTemplateVlanType(v string) {
	o.TemplateVlanType = &v
}

// GetCidr returns the Cidr field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetCidr() string {
	if o == nil || o.Cidr == nil {
		var ret string
		return ret
	}
	return *o.Cidr
}

// GetCidrOk returns a tuple with the Cidr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetCidrOk() (*string, bool) {
	if o == nil || o.Cidr == nil {
		return nil, false
	}
	return o.Cidr, true
}

// HasCidr returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasCidr() bool {
	if o != nil && o.Cidr != nil {
		return true
	}

	return false
}

// SetCidr gets a reference to the given string and assigns it to the Cidr field.
func (o *UpdateNetworkApplianceVlanRequest) SetCidr(v string) {
	o.Cidr = &v
}

// GetMask returns the Mask field value if set, zero value otherwise.
func (o *UpdateNetworkApplianceVlanRequest) GetMask() int32 {
	if o == nil || o.Mask == nil {
		var ret int32
		return ret
	}
	return *o.Mask
}

// GetMaskOk returns a tuple with the Mask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNetworkApplianceVlanRequest) GetMaskOk() (*int32, bool) {
	if o == nil || o.Mask == nil {
		return nil, false
	}
	return o.Mask, true
}

// HasMask returns a boolean if a field has been set.
func (o *UpdateNetworkApplianceVlanRequest) HasMask() bool {
	if o != nil && o.Mask != nil {
		return true
	}

	return false
}

// SetMask gets a reference to the given int32 and assigns it to the Mask field.
func (o *UpdateNetworkApplianceVlanRequest) SetMask(v int32) {
	o.Mask = &v
}

func (o UpdateNetworkApplianceVlanRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Subnet != nil {
		toSerialize["subnet"] = o.Subnet
	}
	if o.ApplianceIp != nil {
		toSerialize["applianceIp"] = o.ApplianceIp
	}
	if o.GroupPolicyId != nil {
		toSerialize["groupPolicyId"] = o.GroupPolicyId
	}
	if o.VpnNatSubnet != nil {
		toSerialize["vpnNatSubnet"] = o.VpnNatSubnet
	}
	if o.DhcpHandling != nil {
		toSerialize["dhcpHandling"] = o.DhcpHandling
	}
	if o.DhcpRelayServerIps != nil {
		toSerialize["dhcpRelayServerIps"] = o.DhcpRelayServerIps
	}
	if o.DhcpLeaseTime != nil {
		toSerialize["dhcpLeaseTime"] = o.DhcpLeaseTime
	}
	if o.DhcpBootOptionsEnabled != nil {
		toSerialize["dhcpBootOptionsEnabled"] = o.DhcpBootOptionsEnabled
	}
	if o.DhcpBootNextServer != nil {
		toSerialize["dhcpBootNextServer"] = o.DhcpBootNextServer
	}
	if o.DhcpBootFilename != nil {
		toSerialize["dhcpBootFilename"] = o.DhcpBootFilename
	}
	if o.FixedIpAssignments != nil {
		toSerialize["fixedIpAssignments"] = o.FixedIpAssignments
	}
	if o.ReservedIpRanges != nil {
		toSerialize["reservedIpRanges"] = o.ReservedIpRanges
	}
	if o.DnsNameservers != nil {
		toSerialize["dnsNameservers"] = o.DnsNameservers
	}
	if o.DhcpOptions != nil {
		toSerialize["dhcpOptions"] = o.DhcpOptions
	}
	if o.TemplateVlanType != nil {
		toSerialize["templateVlanType"] = o.TemplateVlanType
	}
	if o.Cidr != nil {
		toSerialize["cidr"] = o.Cidr
	}
	if o.Mask != nil {
		toSerialize["mask"] = o.Mask
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateNetworkApplianceVlanRequest struct {
	value *UpdateNetworkApplianceVlanRequest
	isSet bool
}

func (v NullableUpdateNetworkApplianceVlanRequest) Get() *UpdateNetworkApplianceVlanRequest {
	return v.value
}

func (v *NullableUpdateNetworkApplianceVlanRequest) Set(val *UpdateNetworkApplianceVlanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNetworkApplianceVlanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNetworkApplianceVlanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNetworkApplianceVlanRequest(val *UpdateNetworkApplianceVlanRequest) *NullableUpdateNetworkApplianceVlanRequest {
	return &NullableUpdateNetworkApplianceVlanRequest{value: val, isSet: true}
}

func (v NullableUpdateNetworkApplianceVlanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNetworkApplianceVlanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


